mode: predict
debug: False
load_ckpt: outputs/experiments/vm/checkpoint_best.pkl

components:
  data: predict
  transform: predict
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: outputs/results
  save_name: denoised
