mode: train
debug: False

components:
  data: train
  transform: vm
  system: vm
  model: vm

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00001

trainer:
  epochs: 100
  log_score: True
  score_every_n_epochs: 10
  score_max_samples: 0
  create_submission_on_train_end: True
  submission_use_best: True
  submission_source_dir: outputs/submission
  submission_zip_path: outputs/result.zip

writer:
  __target__: vm
  save_dir: outputs/submission
  save_name: denoised
